customSyntax: "postcss-scss"
extends":
  - stylelint-config-standard
  - stylelint-config-prettier
plugins:
  - stylelint-scss
  - stylelint-order
rules:
  comment-empty-line-before: null
  font-family-name-quotes: always-where-recommended
  function-url-quotes: always
  # https://www.w3.org/TR/selectors/#attribute-selectors
  # http://stackoverflow.com/q/3851091
  selector-attribute-quotes: always
  order/order:
    - - type: at-rule
        hasBlock: false
      - custom-properties
      - declarations
    - unspecified: ignore
      disableFix: true
  order/properties-order:
    - display
    - position
    - top
    - right
    - bottom
    - left

    - flex
    - flex-basis
    - flex-direction
    - flex-flow
    - flex-grow
    - flex-shrink
    - flex-wrap
    - align-content
    - align-items
    - align-self
    - justify-content
    - order

    - box-sizing

    - width
    - min-width
    - max-width

    - height
    - min-height
    - max-height

    - margin
    - margin-top
    - margin-right
    - margin-bottom
    - margin-left

    - padding
    - padding-top
    - padding-right
    - padding-bottom
    - padding-left

    - float
    - clear

    - resize

    - columns
    - column-count
    - column-gap
    - column-fill
    - column-rule
    - column-span
    - column-width

    - grid-gap
    - grid-template-columns

    - animation
    - animation-name
    - animation-timing-function

    - transform
    - transform-box
    - transform-origin
    - transform-style

    - transition
    - transition-delay
    - transition-duration
    - transition-property
    - transition-timing-function

    # Border

    - border
    - border-top
    - border-right
    - border-bottom
    - border-left
    - border-width
    - border-top-width
    - border-right-width
    - border-bottom-width
    - border-left-width

    - border-style
    - border-top-style
    - border-right-style
    - border-bottom-style
    - border-left-style

    - border-radius
    - border-top-left-radius
    - border-top-right-radius
    - border-bottom-left-radius
    - border-bottom-right-radius

    - border-color
    - border-top-color
    - border-right-color
    - border-bottom-color
    - border-left-color

    - outline
    - outline-color
    - outline-offset
    - outline-style
    - outline-width

    # Background

    - background
    - background-attachment
    - background-clip
    - background-color
    - background-image
    - background-repeat
    - background-position
    - background-size

    - fill

    - opacity

    # Text

    - color

    - font
    - font-family
    - font-size
    - font-smoothing
    - font-style
    - font-variant
    - font-weight

    - letter-spacing
    - line-height
    - list-style

    - text-align
    - text-decoration
    - text-indent
    - text-overflow
    - text-rendering
    - text-shadow
    - text-transform
    - text-wrap

    - white-space
    - word-spacing

    # Cursor

    - cursor
    - pointer-events
    - user-select

    # Other

    - appearance
    - border-collapse
    - border-spacing
    - box-shadow
    - caption-side
    - content
    - empty-cells
    - overflow
    - overflow-x
    - overflow-y
    - quotes
    - speak
    - table-layout
    - vertical-align
    - visibility
    - will-change
    - z-index
  declaration-property-unit-allowed-list:
    font-size:
      - "rem"
      - "em"
  # The following prefix rules are enabled since we use autoprefixer
  at-rule-no-vendor-prefix: true
  media-feature-name-no-vendor-prefix: true
  selector-no-vendor-prefix: true
  value-no-vendor-prefix: true
  # Usually if you're nesting past 3 levels deep there's a problem
  max-nesting-depth: 3
  # Because we adhere to BEM we can limit the amount of necessary compound selectors. Most should
  # just be 1 level selector. However, modifiers can introduce an additional compound selector.
  # Furthermore, generic qualifying selectors (e.g. `[dir="rtl"]`) can introduce yet another level.
  selector-max-compound-selectors: 4
  # For specificity: disallow IDs (0). Allow for complex combinations of classes, pseudo-classes,
  # attribute modifiers based on selector-max-compound-selectors, plus an addition for
  # pseudo-classes (4). Allow for pseudo-elements (1).
  selector-max-specificity: 0,4,1
